[platformio]
src_dir = main
default_envs = esp32-s3-devkitc-1

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  knolleary/PubSubClient@^2.8

[env:esp32-s3-devkitc-1]
board = esp32-s3-devkitc-1

[env:esp32dev]
board = esp32dev
